import styles from '@/styles/Home.module.css'
import { Butin } from 'bub'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import { Button } from 'ui'
// import {Butin} from 'bub'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Butin />
        <Button />
      </main>
    </>
  )
}
